"""Human-readable Markdown digest of the store (v0.3.10).

The direct answer to the sharpest structural critique of Selvedge's
distribution model: `.selvedge/selvedge.db` is a binary, so the captured
intent that is supposed to be the team's shared record cannot be read in a
pull request, a diff viewer, or a GitHub blob view. Everything about the
product says "this is reviewable history"; the artifact says otherwise.

This renders that history as a Markdown file meant to be committed next to
the store, so the reasoning shows up in review the same way code does.

Two properties make it usable in version control, and both are load-bearing:

- **Deterministic.** Same store, same bytes. No timestamps-of-generation, no
  dict iteration order, no LLM. Regenerating without new events must produce
  a zero-line diff, or the file becomes noise everyone learns to skip.
- **Stably anchored.** Each entity's heading anchor is derived from its path,
  so a link to a decision keeps working as the document grows. Sections are
  ordered by rule, not by insertion.

Ordering puts reverted and superseded entities first. That is the same
precision-over-recall judgement the rest of the release makes: the expensive
failure is re-implementing something the team already killed, so the
document leads with what not to do rather than with a chronology.
"""

from __future__ import annotations

_REVERTED = "reverted"
_REOPENED = "reopened"

#: Section order. Reverted first — a reader skimming the top of the file
#: should hit the decisions that would cost them the most to rediscover.
_STATUS_ORDER = (_REVERTED, _REOPENED, "active")

_STATUS_HEADINGS = {
    _REVERTED: ("Tried and reverted", "Do not re-implement these without superseding first."),
    _REOPENED: ("Re-opened", "Previously reverted, then explicitly re-opened."),
    "active": ("Active decisions", "Current state, with the reasoning behind it."),
}


def _anchor(entity_path: str) -> str:
    """A stable, GitHub-compatible anchor slug for an entity path.

    Derived purely from the path so it survives new events, reordering, and
    regeneration — a link into this document has to keep working or nobody
    will link into it.
    """
    slug = []
    for ch in entity_path.lower():
        if ch.isalnum():
            slug.append(ch)
        elif ch in " -_":
            slug.append("-")
        # Everything else (., /, ::) is dropped, matching GitHub's slugger.
    return "".join(slug).strip("-")


def _escape(text: str) -> str:
    """Neutralize Markdown control characters in stored free text.

    Reasoning is written by agents and can contain backticks, pipes and
    underscores. Rendering it raw would let one event's text break the
    document's structure — and this file is committed, so a broken render is
    a permanent artifact rather than a transient glitch.
    """
    return (
        text.replace("\\", "\\\\")
        .replace("|", "\\|")
        .replace("`", "\\`")
        .replace("*", "\\*")
        .replace("_", "\\_")
        .replace("\r\n", " ")
        .replace("\n", " ")
        .strip()
    )


def _group_by_entity(events: list[dict]) -> dict[str, list[dict]]:
    """Events grouped by entity path, each group oldest-first."""
    grouped: dict[str, list[dict]] = {}
    for event in events:
        grouped.setdefault(event["entity_path"], []).append(event)
    for trail in grouped.values():
        trail.sort(key=lambda e: (e["timestamp"], e["id"]))
    return grouped


def _status_of(trail: list[dict], removal_types: frozenset[str]) -> str:
    """Derive an entity's standing verdict from its trail.

    Mirrors `storage._derive_path_status` rather than reading a stored field,
    so this document can never disagree with what `blame` reports.
    """
    latest = trail[-1]
    if latest["change_type"] in removal_types:
        return _REVERTED
    if latest["change_type"] == "supersede":
        return _REOPENED
    return "active"


def render_markdown(events: list[dict], title: str = "Selvedge decision log") -> str:
    """Render events as a deterministic Markdown digest.

    ``events`` is any list of event dicts from the storage read paths. Order
    of the input does not matter — everything is re-sorted here, which is what
    makes the output stable across regenerations.
    """
    from ..storage import _REMOVAL_CHANGE_TYPES

    lines = [
        f"# {title}",
        "",
        "Generated by `selvedge export --format markdown`. Do not edit by hand —",
        "regenerate instead. The database in `.selvedge/` remains the source of",
        "truth; this file exists so the captured reasoning is reviewable in a",
        "diff, which a binary store is not.",
        "",
    ]

    if not events:
        lines += ["_No change events recorded yet._", ""]
        return "\n".join(lines)

    grouped = _group_by_entity(events)
    by_status: dict[str, list[str]] = {status: [] for status in _STATUS_ORDER}
    for entity_path, trail in grouped.items():
        by_status[_status_of(trail, _REMOVAL_CHANGE_TYPES)].append(entity_path)

    counts = ", ".join(
        f"{len(by_status[s])} {_STATUS_HEADINGS[s][0].lower()}"
        for s in _STATUS_ORDER
        if by_status[s]
    )
    noun = "entity" if len(grouped) == 1 else "entities"
    lines += [f"{len(grouped)} {noun} — {counts}.", ""]

    for status in _STATUS_ORDER:
        paths = sorted(by_status[status])
        if not paths:
            continue
        heading, blurb = _STATUS_HEADINGS[status]
        lines += [f"## {heading}", "", blurb, ""]
        for entity_path in paths:
            lines += _render_entity(entity_path, grouped[entity_path])

    return "\n".join(lines).rstrip() + "\n"


def _render_entity(entity_path: str, trail: list[dict]) -> list[str]:
    """One entity's section: heading, constraint, then its trail oldest-first."""
    lines = [f"### `{entity_path}` <a id=\"{_anchor(entity_path)}\"></a>", ""]

    # A constraint is the most reusable thing in a trail — the testable
    # principle rather than the narrative — so it goes above the timeline.
    constraints = [e["constraint"] for e in trail if e.get("constraint")]
    if constraints:
        lines += [f"**Constraint:** {_escape(constraints[-1])}", ""]
    stale_when = [e["stale_when"] for e in trail if e.get("stale_when")]
    if stale_when:
        lines += [f"**Revisit when:** {_escape(stale_when[-1])}", ""]

    for event in trail:
        when = event["timestamp"][:10]
        who = f" — {_escape(event['agent'])}" if event.get("agent") else ""
        reasoning = _escape(event["reasoning"]) or "_no reasoning recorded_"
        lines.append(f"- **{event['change_type']}** ({when}{who}): {reasoning}")
        if event.get("revisit_after"):
            lines.append(f"  - revisit after: {_escape(event['revisit_after'])}")
        if event.get("changeset_id"):
            lines.append(f"  - changeset: `{_escape(event['changeset_id'])}`")
    lines.append("")
    return lines
